### ISSUE TITLE
We need a readme :)

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform-lazybones-templates#1]
I think this should contain a link to the DP project at github, a short description of lazybones and a step by step tutorial to create new project.

**Comment by madmas** [comment]
Yes, absolutely, it's WIP, together with a blog post about how to use the template :)

**Comment by hendrikebbers** [comment]
Can you add a link to the Dolphin Platform GitHub Repo :) I think this is more important than a link to the DO website. Do you agree?

**Comment by madmas** [comment]
Agreed, I added it. As the website would gives a nice introduction to DP, I left the link in there as well :)

**Comment by hendrikebbers** [comment]
Perfect :) I added a link to the this project on the readme of the main dolphin platform repo ;)
